variable "create" {
  description = "Enables the creation of ressources by this module"
  default     = true
  type        = bool
}

variable "prefix" {
  description = "Prefix that is used to prefix all ressources that are generated by this module"
  default     = ""
  type        = string
}

variable "cron_expression" {
  description = "Decides when to trigger the associated lambda"
  type        = string
}
